# Problem Statement 1

Problem Statement 1:Write a function so that the columns of the output matrix are powers of the inputvector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1. HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

In [120]:
def vandermore(x,increasing=False):
    import numpy as np
    d = len(x)
    N = int(input('Enter the power value: '))
    result = np.zeros((d,d))
    if increasing == False:
        for i in range(d):
            for j in range(d):
                result[[i],[j]] = x[i]**(N-j-1)
        return result
    elif increasing == True:
        for i in range(d):
            for j in range(d):
                result[[i],[j]] = x[i]**(j)
        return result   

In [121]:
l = [1,2,3,4]

In [122]:
vandermore(l,True)

Enter the power value: 4


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.],
       [ 1.,  4., 16., 64.]])

In [123]:
vandermore(l,False)

Enter the power value: 4


array([[ 1.,  1.,  1.,  1.],
       [ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.],
       [64., 16.,  4.,  1.]])

In [124]:
vandermore(l)

Enter the power value: 4


array([[ 1.,  1.,  1.,  1.],
       [ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.],
       [64., 16.,  4.,  1.]])

# Problem Statement 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0,the k-th moving average of the given sequence is defined as follows:\
The moving average sequence has n-k+1 elements as shown below.\
The moving averages with k=4 of a ten-value sequence (n=10) is shown below\
i     1  2  3  4  5  6  7  8  9 10\
======= == == == == == == == == ==\
Input 10 20 30 40 50 60 70 80 90 100 \
y1 25 = (10+20+30+40)/4\
y2 35 = (20+30+40+50)/4\
y3 45 = (30+40+50+60)/4\
y4 55 = (40+50+60+70)/4\
y5 65 = (50+60+70+80)/4\
y6 75 = (60+70+80+90)/4\
y7 85 = (70+80+90+100)/4\
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question:\
Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [161]:
def moving_average(l,k):
    # k is moving average window
    # l is sequence of n values
    import numpy as np
    d = np.array(l)
    n = len(l)
    result = np.zeros(n-k+1)
    for i in range(n-k+1):
        window = d[0+i:k+i]
        result[i] = window.mean()
    return result
        
        

In [162]:
h = [3,5,7,2,8,10,11,65,72,81,99,100,150]

In [163]:
moving_average(h,3)


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])